# SITE CONFIGURATION
baseurl: "/juliarainbowx.github.io-blog"
url: "https://juliarainbowx.github.io/juliarainbowx.github.io-blog/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "My Blog"
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Blog about web technologies, self-development and interesting things in ordinary life." # used by search engines

  # Header and footer text
  header_text: >
     <p>REMEMBER: YOU'LL NEVER BE GREATER THAN YOURSELF</p>
     
  header_text_feature_image: "assets/img/sample_feature_img.png"
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: "jukostyuchenko@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "juliarainbowx"
  flickr:
  gitlab:
  github: "juliarainbowx"
  google_plus:
  instagram: "juliarainbowx"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "juliarainbowx"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
